- name: Update OS software version on VM
  hosts: virtualmachines
  become: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true
